# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=20)),
                ('Last_Name', models.CharField(max_length=20)),
                ('Username', models.CharField(max_length=20)),
                ('MobNo', models.IntegerField()),
            ],
        ),
    ]
