# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 12:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='MobNo',
            new_name='phone_number',
        ),
    ]
