# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-07-03 12:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phonenumber', '0002_auto_20180703_1755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
